'use client';

// The five platform URL inputs. Generated by mapping over PLATFORMS, so adding
// a service means one entry in lib/platforms.ts and nothing here. Shared by the
// show settings form and the per-episode override section.
import { INPUT } from '@/components/admin/upload-form';
import { PLATFORMS, type PlatformId, type PlatformLinks } from '@/lib/platforms';

export function PlatformLinkFields({
  value,
  onChange,
  placeholder,
}: {
  value: PlatformLinks;
  onChange: (next: PlatformLinks) => void;
  /** Per-platform placeholder, e.g. the show-level link an episode inherits. */
  placeholder?: (id: PlatformId) => string;
}) {
  return (
    <div className="space-y-4">
      {PLATFORMS.map((platform) => (
        <label key={platform.id} className="block">
          <span className="flex items-center gap-2 text-sm font-semibold text-foreground mb-1.5">
            <svg
              viewBox="0 0 24 24"
              fill={platform.color}
              aria-hidden="true"
              focusable="false"
              className="w-4 h-4 shrink-0"
            >
              <path d={platform.path} />
            </svg>
            {platform.label}
          </span>
          <input
            type="url"
            inputMode="url"
            value={value[platform.id] ?? ''}
            onChange={(e) => onChange({ ...value, [platform.id]: e.target.value })}
            className={INPUT}
            placeholder={placeholder?.(platform.id) ?? 'https://…'}
          />
        </label>
      ))}
    </div>
  );
}
