# Production PM2 ecosystem config — for Hostinger Node.js hosting
module.exports = {
  apps: [
    {
      name: 'mindset-api',
      script: './apps/api/dist/index.js',
      cwd: '.',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 4000,
      },
      env_production: {
        NODE_ENV: 'production',
      },
      out_file: './logs/api-out.log',
      error_file: './logs/api-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_memory_restart: '512M',
      restart_delay: 3000,
      watch: false,
      autorestart: true,
    },
    {
      name: 'mindset-web',
      script: 'node_modules/.bin/next',
      args: 'start -p 3000',
      cwd: './apps/web',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      out_file: './logs/web-out.log',
      error_file: './logs/web-error.log',
      max_memory_restart: '512M',
      restart_delay: 3000,
      watch: false,
      autorestart: true,
    },
    {
      name: 'mindset-admin',
      script: 'node_modules/.bin/next',
      args: 'start -p 3001',
      cwd: './apps/admin',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      out_file: './logs/admin-out.log',
      error_file: './logs/admin-error.log',
      max_memory_restart: '256M',
      restart_delay: 3000,
      watch: false,
      autorestart: true,
    },
  ],
};
